In [ ]:
import pandas as pd
import requests
from bs4 import BeautifulSoup

In [ ]:
headers={'User-Agent':'Mozilla/5.0 (Windows NT 6.3; Win 64 ; x64) Apple WeKit /537.36(KHTML , like Gecko) Chrome/80.0.3987.162 Safari/537.36'}
wp = requests.get('https://www.flipkart.com/search?q=samsung+mobiles&sid=tyy%2C4io&as=on&as-show=on&otracker=AS_QueryStore_OrganicAutoSuggest_1_9_sc_na_ps&otracker1=AS_QueryStore_OrganicAutoSuggest_1_9_sc_na_ps&as-pos=1&as-type=RECENT&suggestionId=samsung+mobiles%7CMobiles&requestId=255ec6c6-8331-4ca1-8c67-652956cbc66f&as-backfill=on',headers=headers).text

In [ ]:
soup=BeautifulSoup(wp,'lxml')

In [ ]:
mobiles=soup.find_all('div',class_='_2kHMtA')

In [ ]:
len(mobiles)

24

In [ ]:
name=[]
rating=[]
ori_price=[]
price=[]
highlight=[]

for i in mobiles:

  name.append(i.find('div',class_='_4rR01T').text.strip())
  rating.append(i.find('div',class_='_3LWZlK').text.strip())
  ori_price.append(i.find('div',class_='_3I9_wc _27UcVY').text.strip())
  price.append(i.find('div',class_='_30jeq3 _1_WHN1').text.strip())
  highlight.append(i.find('ul').text.strip())

In [ ]:
df=pd.DataFrame({'Mobile':name,'Rating':rating,'Ori_price':ori_price,'Price':price,'Highlight':highlight})

In [ ]:
df

,Mobile,Rating,Ori_price,Price,Highlight
0,"SAMSUNG Galaxy F04 (Opal Green, 64 GB)",4.3,"₹11,499","₹8,499",4 GB RAM | 64 GB ROM | Expandable Upto 1 TB16....
1,"SAMSUNG Galaxy F13 (Waterfall Blue, 64 GB)",4.3,"₹14,999","₹10,999",4 GB RAM | 64 GB ROM | Expandable Upto 1 TB16....
2,"SAMSUNG Galaxy M33 5G (Emarld Brown, 128 GB)",4.2,"₹24,999","₹16,358",6 GB RAM | 128 GB ROM16.76 cm (6.6 inch) Displ...
3,"SAMSUNG Galaxy F13 (Waterfall Blue, 128 GB)",4.3,"₹16,999","₹11,999",4 GB RAM | 128 GB ROM | Expandable Upto 1 TB16...
4,"SAMSUNG Galaxy M04 (Light Green, 64 GB)",4.1,"₹11,999","₹7,947",4 GB RAM | 64 GB ROM16.51 cm (6.5 inch) HD+ Di...
5,"SAMSUNG Galaxy F04 (Jade Purple, 64 GB)",4.3,"₹11,499","₹8,499",4 GB RAM | 64 GB ROM | Expandable Upto 1 TB16....
6,"SAMSUNG Galaxy F13 (Nightsky Green, 128 GB)",4.3,"₹16,999","₹11,999",4 GB RAM | 128 GB ROM | Expandable Upto 1 TB16...
7,"SAMSUNG Galaxy F13 (Sunrise Copper, 64 GB)",4.3,"₹14,999","₹10,999",4 GB RAM | 64 GB ROM | Expandable Upto 1 TB16....
8,SAMSUNG Guru Music 2 SM-B315E,4.2,"₹2,442","₹2,150",Expandable Upto 16 GB5.08 cm (2 inch) QVGA Dis...
9,"SAMSUNG Galaxy F13 (Nightsky Green, 64 GB)",4.3,"₹14,999","₹10,999",4 GB RAM | 64 GB ROM | Expandable Upto 1 TB16....
10,"SAMSUNG Galaxy F14 5G (GOAT Green, 128 GB)",4.2,"₹18,490","₹15,490",6 GB RAM | 128 GB ROM | Expandable Upto 1 TB16...
11,"SAMSUNG Galaxy F14 5G (B.A.E. Purple, 128 GB)",4.2,"₹18,490","₹15,490",6 GB RAM | 128 GB ROM | Expandable Upto 1 TB16...
12,"SAMSUNG Galaxy F23 5G (Aqua Blue, 128 GB)",4.3,"₹23,999","₹16,999",6 GB RAM | 128 GB ROM | Expandable Upto 1 TB16...
13,"SAMSUNG Galaxy F14 5G (OMG Black, 128 GB)",4.2,"₹18,490","₹15,490",6 GB RAM | 128 GB ROM | Expandable Upto 1 TB16...
14,"SAMSUNG Galaxy F14 5G (GOAT Green, 128 GB)",4.2,"₹17,490","₹14,490",4 GB RAM | 128 GB ROM | Expandable Upto 1 TB16...
15,"SAMSUNG Galaxy F23 5G (Copper Blush, 128 GB)",4.3,"₹23,999","₹16,999",6 GB RAM | 128 GB ROM | Expandable Upto 1 TB16...
16,"SAMSUNG Galaxy F23 5G (Forest Green, 128 GB)",4.3,"₹23,999","₹16,999",6 GB RAM | 128 GB ROM | Expandable Upto 1 TB16...
17,"SAMSUNG Galaxy M04 (Dark Blue, 64 GB)",4.1,"₹11,499","₹7,880",4 GB RAM | 64 GB ROM | Expandable Upto 1 TB16....
18,"SAMSUNG Galaxy F14 5G (B.A.E. Purple, 128 GB)",4.2,"₹17,490","₹14,490",4 GB RAM | 128 GB ROM | Expandable Upto 1 TB16...
19,"SAMSUNG Galaxy M33 5G (Deep Ocean Blue, 128 GB)",4.2,"₹25,999","₹17,769",8 GB RAM | 128 GB ROM16.76 cm (6.6 inch) Displ...
20,"SAMSUNG Galaxy F14 5G (OMG Black, 128 GB)",4.2,"₹17,490","₹14,490",4 GB RAM | 128 GB ROM | Expandable Upto 1 TB16...
21,"SAMSUNG Galaxy S20 FE 5G (Cloud Navy, 128 GB)",4.2,"₹74,999","₹30,449",8 GB RAM | 128 GB ROM16.51 cm (6.5 inch) Displ...
22,"SAMSUNG Galaxy M33 5G (Mystique Green, 128 GB)",4.2,"₹25,999","₹17,574",8 GB RAM | 128 GB ROM16.76 cm (6.6 inch) Displ...
23,SAMSUNG Guru Music 2,4.3,"₹2,499","₹2,490",NA ROM5.08 cm (2 inch) NA Display800 mAh Batte...

In [ ]:
df.shape

(24, 5)